stop-words = "stopwords.txt"
prefix = "."
dataset = "diseases"
index = "idx"
corpus = "file.toml"
uninvert = true
[[analyzers]]
	method = "ngram-word"
	ngram = 1
	[[analyzers.filter]]
		type = "icu-tokenizer"
	[[analyzers.filter]]
		max = 35
		type = "length"
		min = 2
