prefix = "."
stop-words = "stopwords.txt"

dataset = "diseases"
corpus = "file.toml"
index = "idx"
uninvert = true # create the forward index by un-inverting the
                # inverted index; can save some processing time
                # when using both indexes

[[analyzers]]
method = "ngram-word"
ngram = 1
    [[analyzers.filter]]
    type = "icu-tokenizer"

    [[analyzers.filter]]
    type = "length"
    min = 2
    max = 35
